#!/usr/bin/env bash
#Write infinity loop of with sleep 2
#+ a sleep 2 in between each iteration

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done


